version: '3.4'

services:
  geekbot:
    image: geekbot
    build: .
    environment:
      - main_config=/app/configs/main.properties
    volumes:
        - "./Config/Config.properties:/app/configs/main.properties"
