name: Publish

on: 
  push: 
    branches:
      - release
    
jobs:      
  build:
    name: Build artifact with gradle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./build/libs/**/*
          if-no-files-found: error
          retention-days: 1
          
  deploy:
    name: Create and push docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v2
        
      - name: Download Gradle build artifact
        uses: actions/download-artifact@v1
        with:
          name: package
          path: ./build/libs
        
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build
        id: dockerhub_push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: legendarygeek/geekbot:latest
          tag_with_ref: true
