name: Build and Push Docker image
on:
  push:
    branches: [ release ]
jobs:      
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Builder instance name
        id: builder name
        run: echo ${{ steps.buildx.outputs.name }}
        
      - name: Available platforms
        id: avail platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: Login to DockerHub
        id: dockerhub login
        uses: docker/login-action@v1 
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Push to Docker Hub
        id: dockerhub push
        uses: docker/build-push-action@v2
        with:
          repository: legendarygeek/geekbot
          tag_with_ref: true
  
