name: Build and Push Docker image
on:
  push:
    branches: [ release ]
jobs:      
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew distZip
        
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
        
      - name: Builder instance name
        id: builder_name
        run: echo ${{ steps.buildx.outputs.name }}
        
      - name: Available platforms
        id: avail_platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: Login to DockerHub
        id: dockerhub_login
        uses: docker/login-action@v1.6.0 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push to Docker Hub
        id: dockerhub_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: legendarygeek/geekbot
  
